### ISSUE TITLE
MoveCursorToCorner incorrect behavior 

### ISSUE THREAD

**Issue by Walter-Neils** [hyprland-community/hyprland-rs#213]
I was playing around with the library and ran into some behavior I don't think is correct regarding cursor movement. I'm extremely new to both rust and hyprland, so apologies if this issue is in error. 

# `Corner::*` -> actual cursor position
| Requested Cursor Destination        | Resulting Cursor Position |
|---------------------|---------------------------|
| Corner::BottomLeft  | Top Left                  |
| Corner::BottomRight | Top Right                 |
| Corner::TopLeft     | Bottom Right              |
| Corner::TopRight    | Bottom Left               |

# Minimal Reproduction
```rust
use hyprland::dispatch::*;
use std::{thread, time};

fn main() {
    let delay = time::Duration::from_secs(5);
    let targets: [Corner; 4] = [
        Corner::BottomLeft,
        Corner::BottomRight,
        Corner::TopLeft,
        Corner::TopRight,
    ];
    loop {
        for target in &targets {
            Dispatch::call(DispatchType::MoveCursorToCorner(target.clone()))
                .expect("Failed to move cursor");
            let target_as_string = match target {
                Corner::BottomLeft => "bottom left",
                Corner::BottomRight => "bottom right",
                Corner::TopLeft => "top left",
                Corner::TopRight => "top right",
            };
            println!("Moved cursor to {target_as_string}");
            thread::sleep(delay);
        }
    }
}
```
# Minimal Reproduction's `Cargo.toml`
```toml
[package]
name = "test-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyprland = { git = "https://github.com/hyprland-community/hyprland-rs", branch = "master" }

```

# Related Information
- `hyprland` version: `0.39.1-5`, installed via pacman
- `hyprland-rs` master branch commit: `1de892551a060d9bb8c2afc1f2eb1c83867a836e`
  - Note: this issue occurs both when using the git master branch OR the standard crate
- Output of `rustup show`:
```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/$USER/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.77.2 (25ef9e3d8 2024-04-09)
```
Note that I replaced my username with `$USER`.
