### ISSUE TITLE
Wrong window_class in WindowEventData using the window change handler

### ISSUE THREAD

**Issue by zd4y** [hyprland-community/hyprland-rs#65]
Hello, using the window change handler and moving focus to firefox with this video opened https://www.youtube.com/watch?v=aUiazUxP0j8 gives the wrong window_class and window_title:

```
Some(
    WindowEventData {
        window_class: "firefox,GrapheneOS: first impressions, stumbling blocks",
        window_title: " and opinions - YouTube — Mozilla Firefox",
        window_address: Address(
            "597b290",
        ),
    },
)
```

This is the code:

```rust
use hyprland::event_listener::EventListener;

fn main() -> hyprland::Result<()> {
    let mut event_listener = EventListener::new();
    event_listener.add_active_window_change_handler(|data| println!("{data:#?}"));
    event_listener.start_listener()
}
```

`Cargo.toml`:

```toml
[package]
name = "hyprlandtest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyprland = { git = "https://github.com/hyprland-community/hyprland-rs", branch = "master" }
```

Output from `hyprctl clients`:
```
Window 597b290 -> GrapheneOS: first impressions, stumbling blocks, and opinions - YouTube — Mozilla Firefox:
	mapped: 1
	hidden: 0
	at: 22,22
	size: 931,1006
	workspace: 1 (1:  )
	floating: 0
	monitor: 0
	class: firefox
	title: GrapheneOS: first impressions, stumbling blocks, and opinions - YouTube — Mozilla Firefox
	initialClass: firefox
	initialTitle: Mozilla Firefox
	pid: 1883
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
```
